blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/PrathxmOp/dab-downloader/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/PrathxmOp/dab-downloader#readme
    about: Read the comprehensive documentation and usage guide
  - name: 🔒 Security Issue
    url: https://github.com/PrathxmOp/dab-downloader/security/advisories/new
    about: Report a security vulnerability (private disclosure)