name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand and evaluate your request.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: This feature would benefit multiple users, not just my specific use case
          required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Download functionality
        - Search and discovery
        - Metadata handling
        - User interface/experience
        - Performance improvement
        - Integration (Spotify, Navidrome, etc.)
        - Configuration/settings
        - Quality of life improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: "Add support for downloading from YouTube Music playlists"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "Currently, users can only import from Spotify playlists, but many users also have YouTube Music collections..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution in detail
      placeholder: "Add a new command like `./dab-downloader youtube <youtube_music_playlist_url>` that..."
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Alternatively, this could be implemented as..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. User wants to migrate their YouTube Music library
        2. DJ needs to quickly download tracks from a collaborative playlist
        3. ...
      value: |
        1. 
        2. 
        3. 

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, mockups, or examples
      placeholder: "Links to similar features in other tools, mockups, technical considerations..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be interested in contributing code for this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide domain expertise or guidance