name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions for GITHUB_TOKEN to create releases and upload assets
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'

    - name: Download Go Modules
      run: |
        go mod tidy
        go mod download

    - name: Get current date and commit hash for versioning
      id: version_info
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "TAG_NAME=v${{ env.DATE }}-${{ env.COMMIT }}" >> $GITHUB_ENV

    - name: Build for Linux
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ env.TAG_NAME }}" -o dab-downloader-linux-amd64
    - name: Build for Windows
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ env.TAG_NAME }}" -o dab-downloader-windows-amd64.exe
    - name: Build for macOS
      run: |
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ env.TAG_NAME }}" -o dab-downloader-darwin-amd64

    - name: Create and Push Git Tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset Linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dab-downloader-linux-amd64
        asset_name: dab-downloader-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset Windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dab-downloader-windows-amd64.exe
        asset_name: dab-downloader-windows-amd64.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset macOS
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dab-downloader-darwin-amd64
        asset_name: dab-downloader-darwin-amd64
        asset_content_type: application/octet-stream
